#!/usr/bin/env python3
"""Regenerates `templates_generated.rs` from the wwPDB Chemical Component
Dictionary (CCD).

Not part of the build -- vv-core ships the generated table, not a
runtime download (see `templates.rs` module doc). Run this by hand only
to refresh the table (e.g. to add a residue), from anywhere:

    python3 crates/vv-core/src/bonds/gen_templates.py

Fetches each component's `_chem_comp_bond` loop from
https://files.rcsb.org/ligands/download/<ID>.cif, caching the raw CIF in
`ccd_cache/` next to this script so re-runs don't re-fetch.
"""
import os
import re
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CCD_CACHE = os.path.join(SCRIPT_DIR, "ccd_cache")
OUT_PATH = os.path.join(SCRIPT_DIR, "templates_generated.rs")
CCD_URL = "https://files.rcsb.org/ligands/download/{id}.cif"

# Residue names to emit, in table order, plus non-CCD aliases (see
# templates.rs module doc for why the protonation-state names below are
# hand-aliased instead of fetched under their own name).
AMINO_ACIDS = [
    "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE",
    "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL",
]
AMINO_ACID_ALIASES = {
    "HSD": "HIS", "HSE": "HIS", "HSP": "HIS",
    "HID": "HIS", "HIE": "HIS", "HIP": "HIS",
    "CYX": "CYS", "CYM": "CYS",
    "ASH": "ASP", "GLH": "GLU", "LYN": "LYS",
}
NUCLEOTIDES = ["A", "C", "G", "U", "DA", "DC", "DG", "DT", "DU"]
NUCLEOTIDE_ALIASES = {"ADE": "A", "CYT": "C", "GUA": "G", "URA": "U", "THY": "DT"}
GLYCANS = ["NAG", "MAN", "BMA", "GAL", "FUC", "SIA", "NAN", "GLC"]
COFACTORS = ["HEM", "HEC"]
WATER = ["HOH"]
WATER_ALIASES = {
    "WAT": "HOH", "TIP3": "HOH", "TIP4": "HOH", "SPC": "HOH", "H2O": "HOH", "DOD": "HOH",
}

# Force-field terminal-atom aliases: not part of a free-standing amino
# acid's CCD entry (which has no chain neighbor), added by hand so a
# residue actually terminating a chain bonds them regardless of which
# convention (legacy PDB OXT, CHARMM OT1/OT2, AMBER H1-H3) named them.
# All single bonds (H additions and an alternate carboxylate oxygen).
TERMINAL_EXTRAS = [("C", "OT1", "Single"), ("C", "OT2", "Single"),
                    ("N", "H1", "Single"), ("N", "H2", "Single"), ("N", "H3", "Single")]

# `_chem_comp_bond.value_order` -> `BondOrder` variant. CCD Kekulizes
# aromatic rings as alternating SING/DOUB (see templates.rs module doc),
# so only the rare literal AROM/DELO (undetermined, non-Kekulé) maps to
# Aromatic; anything else unrecognized defaults to Single.
ORDER_MAP = {
    "SING": "Single", "DOUB": "Double", "TRIP": "Triple",
    "AROM": "Aromatic", "DELO": "Aromatic", "QUAD": "Triple",
}


def fetch(comp_id):
    os.makedirs(CCD_CACHE, exist_ok=True)
    path = os.path.join(CCD_CACHE, f"{comp_id}.cif")
    if not os.path.exists(path):
        with urllib.request.urlopen(CCD_URL.format(id=comp_id), timeout=15) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, encoding="utf-8") as f:
        return f.read()


def tokenize(line):
    return re.findall(r'"[^"]*"|\S+', line)


def parse_bonds(comp_id):
    text = fetch(comp_id)
    m = re.search(r"_chem_comp_bond\.pdbx_ordinal\s*\n(.*?)\n#", text, re.S)
    if not m:
        return []
    bonds = []
    for line in m.group(1).splitlines():
        tok = tokenize(line.strip())
        if len(tok) < 4 or tok[0] != comp_id:
            continue
        order = ORDER_MAP.get(tok[3].strip('"').upper(), "Single")
        bonds.append((tok[1].strip('"'), tok[2].strip('"'), order))
    return bonds


def rust_pairs(triples):
    return ", ".join(f'("{a}", "{b}", BondOrder::{o})' for a, b, o in triples)


def emit_group(out, title, names, alias_map, extras=None):
    out.append(f"\n// {title}")
    for name in names:
        bonds = parse_bonds(name) + (extras or [])
        out.append(f'    ("{name}", &[{rust_pairs(bonds)}]),')
    for alias, parent in alias_map.items():
        bonds = parse_bonds(parent) + (extras or [])
        out.append(f"    // {alias}: alias of {parent} (see module doc).")
        out.append(f'    ("{alias}", &[{rust_pairs(bonds)}]),')


def main():
    out = [
        "// Generated by gen_templates.py -- do not hand-edit.",
        "// Source: wwPDB Chemical Component Dictionary (CCD),",
        "// https://www.wwpdb.org/data/ccd, `_chem_comp_bond` records fetched",
        "// from https://files.rcsb.org/ligands/download/<ID>.cif.",
        "use crate::BondOrder;",
        "#[rustfmt::skip]",
        "pub static TEMPLATES: &[(&str, &[(&str, &str, BondOrder)])] = &[",
    ]
    emit_group(out, "Standard amino acids + force-field protonation aliases",
               AMINO_ACIDS, AMINO_ACID_ALIASES, extras=TERMINAL_EXTRAS)
    emit_group(out, "Nucleotides (RNA/DNA) + legacy 3-letter aliases",
               NUCLEOTIDES, NUCLEOTIDE_ALIASES)
    emit_group(out, "Water", WATER, WATER_ALIASES)
    emit_group(out, "Common glycans", GLYCANS, {})
    emit_group(out, "Heme cofactors (Fe-N porphyrin bonds; axial ligand via explicit file bonds)",
               COFACTORS, {})
    out.append("];")
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
