//! Regenerates `src/antibody/consensus.rs`: per scheme and label, the
//! residue counts of heavy chains in the even half of the reference
//! comparison set (docs/ANTIBODY.md, "Placement by consensus").
//!
//! `cargo test --release -p vv-core --test antibody_consensus_gen -- --ignored`

use std::collections::BTreeMap;
use std::fmt::Write as _;

use vv_core::antibody::ChainType;

mod antibody_common;
use antibody_common::reference::{comparison_set, halves, records, Record, SCHEMES};

const AA: &[u8; 20] = b"ARNDCQEGHILKMFPSTWYV";
/// Labels the placement step scores: heavy FR2, and CDR-H2's tail through FR3.
const LABELS: [(u16, u16); 2] = [(36, 49), (57, 92)];
/// Labels seen in fewer residues are left out; they would score only noise.
const MIN_RESIDUES: u32 = 1;

type Counts = BTreeMap<(u16, u8), [u16; 20]>;

fn tally(recs: &[Record], half: &BTreeMap<String, usize>) -> Counts {
    let mut counts = Counts::new();
    for &i in &comparison_set(recs) {
        let r = &recs[i];
        if r.chain != ChainType::Heavy || half[&r.entry] != 0 {
            continue;
        }
        for (aa, label) in r.sequence.bytes().zip(&r.reference) {
            let scored = LABELS
                .iter()
                .any(|&(lo, hi)| (lo..=hi).contains(&label.number));
            let Some(a) = AA.iter().position(|&x| x == aa).filter(|_| scored) else {
                continue;
            };
            let key = (label.number, label.insertion().map_or(0, |c| c as u8));
            counts.entry(key).or_insert([0; 20])[a] += 1;
        }
    }
    counts
        .into_iter()
        .filter(|(_, c)| c.iter().map(|&n| u32::from(n)).sum::<u32>() >= MIN_RESIDUES)
        .collect()
}

#[test]
#[ignore = "needs fixtures/real/reference; writes src/antibody/consensus.rs"]
fn regenerate_consensus() {
    let mut out = String::from(
        "// Generated by tests/antibody_consensus_gen.rs from the even half of the\n\
         // reference comparison set (Ferdous & Martin 2018); do not edit.\n\n\
         /// Label number, insertion letter (0 for none), residue counts.\n\
         pub(super) type Row = (u16, u8, [u16; 20]);\n\n\
         /// Heavy chains under Kabat, Chothia and Martin numbering.\n\
         #[rustfmt::skip]\n\
         pub(super) const HEAVY: [&[Row]; 3] = [\n",
    );
    let half = halves();
    for (dir, scheme, _) in SCHEMES {
        writeln!(out, "    // {dir}\n    &[").unwrap();
        for ((number, ins), c) in tally(&records(dir, scheme), &half) {
            writeln!(out, "        ({number}, {ins}, {c:?}),").unwrap();
        }
        out.push_str("    ],\n");
    }
    out.push_str("];\n");
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/antibody/consensus.rs");
    std::fs::write(path, out).expect("write consensus.rs");
}
