#!/usr/bin/env python3
"""Regenerates `seeds.rs` from public wwPDB sequences (CC0).

Not part of the build: vv-core ships the generated table. Run by hand to
refresh it, from anywhere:

    python3 crates/vv-core/src/antibody/gen_seeds.py

Fetches https://www.rcsb.org/fasta/entry/<ID> for every ID in
`seed_ids.txt`, caching under `fixtures/real/rcsb_fasta_cache/`. In each
polymer sequence it locates variable-domain anchors (the two conserved
Cys, the FR2 Trp, the FR4 [WF]G.G motif), cuts the four framework
segments at their IMGT lengths, classifies the chain (heavy, kappa,
lambda) from the FR4 motif, and greedily clusters at 90% identity. The
CDRs are discarded: they are variable and the aligner never scores them.
"""
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
CACHE = os.path.join(REPO, "fixtures", "real", "rcsb_fasta_cache")

FR2_PATTERNS = (re.compile(r"W[VIALMF][RKQ][QKRE]"), re.compile(r"W[YFLHV][QLRHK][QKHRE]"))
FR4_MOTIF = re.compile(r"[WF]G.G")
# Residues before the first Cys / FR3 length, by chain type: IMGT columns
# minus the columns the germline leaves empty (docs/ANTIBODY.md).
BEFORE_CYS = {"H": 21, "K": 22, "L": 21}
FR3_LEN = {"H": 38, "K": 36, "L": 36}
IDENTITY = 0.90


def fetch(pdb_id):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, pdb_id + ".fa")
    if not os.path.exists(path):
        url = "https://www.rcsb.org/fasta/entry/" + pdb_id
        with open(path, "wb") as f:
            f.write(urllib.request.urlopen(url, timeout=30).read())
    with open(path) as f:
        return [
            "".join(block.split("\n")[1:])
            for block in f.read().split(">")
            if block.strip()
        ]


def classify(fr4):
    if fr4[0] == "W":
        return "H"
    if re.match(r"FG.GT[KRA][LVA][EDT][IL]K", fr4):
        return "K"
    if re.match(r"FG.GT[KRE][LV][TE]V", fr4) or re.match(r"FG.GT.L.V", fr4):
        return "L"
    return None


def domain(s):
    for c1 in (m.start() for m in re.finditer("C", s)):
        for c2 in (c1 + 55 + m.start() for m in re.finditer("C", s[c1 + 55:c1 + 95])):
            fr4m = FR4_MOTIF.search(s, c2 + 3, c2 + 30)
            fr2 = next(
                (p.search(s, c1 + 8, c1 + 40) for p in FR2_PATTERNS if p.search(s, c1 + 8, c1 + 40)),
                None,
            )
            if not (fr4m and fr2):
                continue
            fr4 = s[fr4m.start():fr4m.start() + 11]
            chain = classify(fr4)
            if chain is None or c1 < BEFORE_CYS[chain]:
                continue
            w = fr2.start()
            seg = (
                s[c1 - BEFORE_CYS[chain]:c1 + 4],
                s[w - 2:w + 15],
                s[c2 - FR3_LEN[chain] + 1:c2 + 1],
                fr4.ljust(11, "-"),
            )
            if len(seg[1]) == 17 and w - 2 > c1 + 4 and c2 - FR3_LEN[chain] + 1 > w + 15:
                return chain, seg
    return None


def identity(a, b):
    pairs = [(x, y) for x, y in zip(a, b) if x != "-" and y != "-"]
    return sum(x == y for x, y in pairs) / max(1, len(pairs))


def main():
    with open(os.path.join(HERE, "seed_ids.txt")) as f:
        ids = [l.strip() for l in f if l.strip()]
    found = {"H": {}, "K": {}, "L": {}}
    for pid in ids:
        for seq in fetch(pid):
            d = domain(seq)
            if d:
                found[d[0]][d[1]] = found[d[0]].get(d[1], 0) + 1
    clusters = {}
    for chain, segs in found.items():
        reps = []
        for seg, count in sorted(segs.items(), key=lambda kv: (-kv[1], kv[0])):
            joined = "".join(seg)
            for rep in reps:
                if identity(joined, "".join(rep["seg"])) >= IDENTITY:
                    rep["weight"] += count
                    break
            else:
                reps.append({"seg": seg, "weight": count})
        clusters[chain] = reps
    write(clusters)


def write(clusters):
    names = {"H": "HEAVY", "K": "KAPPA", "L": "LAMBDA"}
    lines = [
        "// Generated by gen_seeds.py from wwPDB sequences (CC0); do not edit.",
        "",
        "use super::profile::Seed;",
        "",
    ]
    for chain in "HKL":
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub(super) static {names[chain]}: &[Seed] = &[")
        for rep in clusters[chain]:
            fr = ", ".join(f'"{x}"' for x in rep["seg"])
            lines.append(f"    Seed {{ weight: {rep['weight']}, fr: [{fr}] }},")
        lines += ["];", ""]
    with open(os.path.join(HERE, "seeds.rs"), "w", newline="\n") as f:
        f.write("\n".join(lines))
    for chain in "HKL":
        print(chain, len(clusters[chain]), "clusters,", sum(r["weight"] for r in clusters[chain]), "seqs")


if __name__ == "__main__":
    main()
